core/urls.py
from django.urls import path
from . import views
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('', views.inicio.as_view(), name='inicio'),
    path('listado/', views.listadoEquipos.as_view(), name='listado'),
    path('crear/',views.crearEquipos.as_view(), name='crear'),
    path('borrar/<int:pk>', views.borrarEquipos.as_view(), name='borrar'),
    path('modificar/<int:pk>', views.modificarEquipos.as_view(), name='modificar'),

    path('listadoJugador/', views.listadoJugador.as_view(), name='listadoJugador'),
    path('crearJugador/',views.crearJugador.as_view(), name='crearJugador'),
    path('borrarJugador/<int:pk>', views.borrarJugador.as_view(), name='borrarJugador'),
    path('modificarJugador/<int:pk>', views.modificarJugador.as_view(), name='modificarJugador'),

    path('listadoCompeticion/', views.listadoCompeticion.as_view(), name='listadoCompeticion'),
    path('crearCompeticion/',views.crearCompeticion.as_view(), name='crearCompeticion'),
    path('borrarCompeticion/<int:pk>', views.borrarCompeticion.as_view(), name='borrarCompeticion'),
    path('modificarCompeticion/<int:pk>', views.modificarCompeticion.as_view(), name='modificarCompeticion'),

    path('jugadorDetalle/<int:pk>',views.jugadorDetalle.as_view(),name='jugadorDetalle'),
    path('competicionDetalla/<int:pk>',views.competicionDetalle.as_view(),name='competicionDetalle'),
    path('equiposDetalle/<int:pk>',views.equiposDetalle.as_view(),name='equiposDetalle'),

]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

proyectoEquipos/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('accounts/', include('django.contrib.auth.urls')), #para el login
    path('accounts/', include('registration.urls')), #para el login
    path('admin/', admin.site.urls),
    path('', include('core.urls')),
    path('contacto/',include('contacto.urls')),
]

core/models.py
from django.db import models

# Create your models here.

from datetime import date
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

class Competicion(models.Model):
    nombre = models.CharField(max_length=30, verbose_name='Nombre de la competición',blank=False, null=False)
    lugar = models.CharField(max_length=30, verbose_name='Lugar de la competición')
    fechaCreacion = models.DateField(default=date.today,blank=False, null=False, verbose_name='fecha de creacion')
    fechaModificacion = models.DateField(default=date.today,blank=False, null=False, verbose_name='fecha de modificacion')
    responsable = models.ForeignKey(User, on_delete=models.CASCADE)
    foto = models.ImageField(null=True, blank=True, upload_to="imgCompeticion")
    def __str__(self):
        return self.nombre
        
    class Meta:
        verbose_name_plural = "Competicion"
    
class Equipos(models.Model):
    nombre = models.CharField(max_length=30, verbose_name='Nombre del equipo',blank=False, null=False)
    categoria = models.CharField(max_length=30, verbose_name='Nombre de la categoría',blank=False, null=False)
    responsable = models.ForeignKey(User, on_delete=models.CASCADE)
    competicion = models.ManyToManyField(Competicion, verbose_name='Competicion')
    foto = models.ImageField(null=True, blank=True, upload_to="imgEquipo")
    fechaCreacion = models.DateField(default=date.today, blank=False, null=False, verbose_name='fecha de creacion')
    fechaModificacion = models.DateField(default=date.today,blank=False, null=False, verbose_name='fecha de modificacion')

    def __str__(self):
        return self.nombre
    
    class Meta:
        verbose_name_plural = "Equipos"

class Jugador(models.Model):
    nombre = models.CharField(max_length=30, verbose_name='Nombre del Jugador',blank=False, null=False)
    correo = models.EmailField(verbose_name='Correo Electronico')
    responsable = models.ForeignKey(User, on_delete=models.CASCADE)
    edad = models.IntegerField()
    foto = models.ImageField(null=True, blank=True, upload_to="imgJugador")
    equipo = models.ForeignKey(Equipos, on_delete=models.CASCADE)
    fechaCreacion = models.DateField(default=date.today,blank=False, null=False, verbose_name='fecha de creacion')
    fechaModificacion = models.DateField(default=date.today,blank=False, null=False, verbose_name='fecha de modificacion')

    def __str__(self):
        return self.nombre
    
    class Meta:
        verbose_name_plural = "Jugadores"

core/views.py
from typing import Any
from django.http import HttpRequest
from django.http.response import HttpResponse as HttpResponse
from django.views.generic.base import TemplateView
from django.views.generic.list import ListView
from django.views.generic.detail import DetailView
from django.views.generic.edit import CreateView, DeleteView, UpdateView
from django.urls import reverse_lazy
from .models import Equipos, Competicion, Jugador
from django.utils.decorators import method_decorator
from django.contrib.auth.decorators import login_required
from django.core.exceptions import PermissionDenied

# Create your views here.

class inicio (TemplateView):
    template_name='core/index.html'

class listadoEquipos (ListView):
    model = Equipos

@method_decorator(login_required, name='dispatch') #da error si intentas entrar a crear a traves de la url sin estar logado
class crearEquipos(CreateView):
    model = Equipos
    fields = ['nombre','categoria','competicion','fechaCreacion','foto']
    success_url = reverse_lazy('listado')

    def form_valid(self, form): #validador de datos del usuario
        form.instance.responsable = self.request.user #el usuario que esta identificado en el admin es el que crea el articulo por defecto
        return super(crearEquipos,self).form_valid(form)

@method_decorator(login_required, name='dispatch') #lo mismo que con crear pero con borrar
class borrarEquipos(DeleteView):
    model = Equipos
    success_url = reverse_lazy('listado')

    def dispatch(self, request: HttpRequest, *args: Any, **kwargs: Any) -> HttpResponse:
        equipo = self.get_object() #me devuelve el articulo que se quiere modificar
        if equipo.responsable != request.user: #comprobar si el autor es el mismo que el user logeado
            raise PermissionDenied #lanzar un error de permisos
        return super().dispatch(request, *args, **kwargs)

@method_decorator(login_required, name='dispatch')
class modificarEquipos(UpdateView):
    model = Equipos
    fields = ['nombre','categoria','competicion','fechaCreacion']
    template_name_suffix = "_update_form"
    success_url =reverse_lazy('listado')

    def dispatch(self, request: HttpRequest, *args: Any, **kwargs: Any) -> HttpResponse:
        equipo = self.get_object() #me devuelve el articulo que se quiere modificar
        if equipo.responsable != request.user: #comprobar si el autor es el mismo que el user logeado
            raise PermissionDenied #lanzar un error de permisos
        return super().dispatch(request, *args, **kwargs)


########################################################################################################################
    
class listadoJugador (ListView):
    model = Jugador

@method_decorator(login_required, name='dispatch') #da error si intentas entrar a crear a traves de la url sin estar logado
class crearJugador(CreateView):
    model = Jugador
    fields = ['nombre','correo','edad','foto','equipo','fechaCreacion','fechaModificacion']
    success_url = reverse_lazy('listadoJugador')

    def form_valid(self, form): #validador de datos del usuario
        form.instance.responsable = self.request.user #el usuario que esta identificado en el admin es el que crea el articulo por defecto
        return super(crearJugador,self).form_valid(form)

@method_decorator(login_required, name='dispatch') #lo mismo que con crear pero con borrar
class borrarJugador(DeleteView):
    model = Jugador
    success_url = reverse_lazy('listadoJugador')

    def dispatch(self, request: HttpRequest, *args: Any, **kwargs: Any) -> HttpResponse:
        jugador = self.get_object() #me devuelve el articulo que se quiere modificar
        if jugador.responsable != request.user: #comprobar si el autor es el mismo que el user logeado
            raise PermissionDenied #lanzar un error de permisos
        return super().dispatch(request, *args, **kwargs)

@method_decorator(login_required, name='dispatch')
class modificarJugador(UpdateView):
    model = Jugador
    fields = ['nombre','correo','edad','foto','equipo','fechaCreacion','fechaModificacion']
    template_name_suffix = "_update_form"
    success_url =reverse_lazy('listadoJugador')

    def dispatch(self, request: HttpRequest, *args: Any, **kwargs: Any) -> HttpResponse:
        jugador = self.get_object() #me devuelve el articulo que se quiere modificar
        if jugador.responsable != request.user: #comprobar si el autor es el mismo que el user logeado
            raise PermissionDenied #lanzar un error de permisos
        return super().dispatch(request, *args, **kwargs)

#########################################################################################################################
    
class listadoCompeticion (ListView):
    model = Competicion

@method_decorator(login_required, name='dispatch') #da error si intentas entrar a crear a traves de la url sin estar logado
class crearCompeticion(CreateView):
    model = Competicion
    fields = ['nombre','lugar','foto','fechaCreacion','fechaModificacion']
    success_url = reverse_lazy('listadoCompeticion')

    def form_valid(self, form): #validador de datos del usuario
        form.instance.responsable = self.request.user #el usuario que esta identificado en el admin es el que crea el articulo por defecto
        return super(crearCompeticion,self).form_valid(form)

@method_decorator(login_required, name='dispatch') #lo mismo que con crear pero con borrar
class borrarCompeticion(DeleteView):
    model = Competicion
    success_url = reverse_lazy('listadoCompeticion')

    def dispatch(self, request: HttpRequest, *args: Any, **kwargs: Any) -> HttpResponse:
        competicion = self.get_object() #me devuelve el articulo que se quiere modificar
        if competicion.responsable != request.user: #comprobar si el autor es el mismo que el user logeado
            raise PermissionDenied #lanzar un error de permisos
        return super().dispatch(request, *args, **kwargs)

@method_decorator(login_required, name='dispatch')
class modificarCompeticion(UpdateView):
    model = Competicion
    fields = ['nombre','lugar','foto','fechaCreacion','fechaModificacion']
    template_name_suffix = "_update_form"
    success_url =reverse_lazy('listadoCompeticion')

    def dispatch(self, request: HttpRequest, *args: Any, **kwargs: Any) -> HttpResponse:
        competicion = self.get_object() #me devuelve el articulo que se quiere modificar
        if competicion.responsable != request.user: #comprobar si el autor es el mismo que el user logeado
            raise PermissionDenied #lanzar un error de permisos
        return super().dispatch(request, *args, **kwargs)


class jugadorDetalle(DetailView):
    model = Jugador

class competicionDetalle(DetailView):
    model = Competicion

class equiposDetalle(DetailView):
    model=Equipos

core/templates/core/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Competicion y Equipos V2</title>
    <!-- Latest compiled and minified CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet">
    <!-- Latest compiled JavaScript -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js"></script>
</head>
<body>

<nav class="navbar navbar-expand-sm bg-dark navbar-dark">
    <div class="container-fluid">
        <ul class="navbar-nav">
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown">Equipos</a>
                <ul class="dropdown-menu">
                    <li><a class="dropdown-item" href="{% url 'crear' %}">Crear equipo</a></li>
                    <li><a class="dropdown-item" href="{% url 'listado' %}">Lista equipos</a></li>
                </ul>
            </li>
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown">Jugadores</a>
                <ul class="dropdown-menu">
                    <li><a class="dropdown-item" href="{% url 'crearJugador' %}">Crear jugador</a></li>
                    <li><a class="dropdown-item" href="{% url 'listadoJugador' %}">Lista jugadores</a></li>
                </ul>
            </li>
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown">Competiciones</a>
                <ul class="dropdown-menu">
                    <li><a class="dropdown-item" href="{% url 'crearCompeticion' %}">Crear competición</a></li>
                    <li><a class="dropdown-item" href="{% url 'listadoCompeticion' %}">Lista competiciones</a></li>
                </ul>
            </li>
        </ul>
        <ul class="navbar-nav justify-content-end">
            <li class="nav-item">
                <a class="nav-link" href="{% url 'contacto'%}">Contacto</a>
            </li>
            {% if request.user.is_authenticated %}
            <li class="nav-item">
                <a class="nav-link">{{ request.user }}</a>
            </li>
            <li class="nav-item">
                <form action="{% url 'logout' %}" method="post">
                    {% csrf_token %}
                    <input type="submit" class="btn btn-danger" value="Logout">
                </form>
            </li>
            {% else %}
            <li class="nav-item">
                <a class="nav-link" href="{% url 'login' %}">Entrar</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'registro' %}">Registrarse</a>
            </li>
            {% endif %}
        </ul>
      
    </div>
</nav>    

{% block contenido %}
{% endblock %}

</body>
</html>

core/templates/core/competicion_confirm_delete.html
{% extends "core/base.html" %}
{% block contenido %}
<div class="container mt-5">
    <div class="row">
        <div class="col-1"></div>
        <div class="col-10 text-center">
            <form method="post">
                {% csrf_token %}
                <p>¿Seguro que quieres borrar la competicion {{competicion}}?</p>
                {{ form }}
                <input type="submit" value="confirmar" class="btn btn-primary">
                <a href="{% url 'listadoCompeticion' %}" class="btn btn-secondary">Cancelar</a>
            </form>
        </div>
    </div>
</div>

{% endblock %}

core/templates/core/competicion_detail.html
{% extends "core/base.html"%}
{% block contenido %}

<div class="card" style="width: 18rem;">
    {% if competicion.foto %}
    <img class="card-img-top" src="{{ competicion.foto.url }}" alt="{{ competicion.nombre }}">
    {% endif %}
    <div class="card-body">
        <ul class="list-group list-group-flush">
            <li class="list-group-item"><b>Nombre: </b>{{competicion.nombre}}</li>
            <li class="list-group-item"><b>Edad: </b>{{competicion.lugar}}</li>   
            <li class="list-group-item"><b>Equipos:</b></li>
            <ul>
                {% for equipo in competicion.equipos_set.all %}
                <a href="{equipo.url}">
                    <li>{{ equipo.nombre }}</li>
                </a>
                {% endfor %}
            </ul> 
          </ul>
    </div>
  </div>
{% endblock %}

core/templates/core/competicion_list.html
{% extends "core/base.html" %}

{% block contenido %}
  <div class="container">
    <div class="row">
      <div class="col-1"></div>
      <div class="col-10">
        {% for competicion in competicion_list %}
          <div class="card mb-3" style="max-width: 1200px;">
            <div class="row g-0">
              <div class="col-4">
                {% if competicion.foto %}
                  <img src="{{ competicion.foto.url }}" class="img-fluid rounded-start" alt="imagen de {{ competicion.nombre }}">
                {% endif %}
              </div>
              <div class="col-8">
                <div class="card-body">
                  <a href="{% url 'competicionDetalle' competicion.id %}"><h5 class="card-title">{{ competicion.nombre }} </h5></a>
                  <p class="card-text">Lugar: {{ competicion.lugar }}</p>
                  <p class="card-text">Fecha de creacion: {{ competicion.fechaCreacion }}</p>

                  {% if competicion.responsable == request.user %}
                    <p class="card-text">
                      <small class="text-muted">
                        <a href="{% url 'borrarCompeticion' competicion.id %}">borrar</a>
                      </small>
                    </p>
                    <p class="card-text">
                      <small class="text-muted">
                        <a href="{% url 'modificarCompeticion' competicion.id %}">modificar</a>
                      </small>
                    </p>
                  {% endif %}
                </div>
              </div>
            </div>
          </div>
        {% endfor %}
      </div>
      <div class="col-1"></div>
    </div>
  </div>
{% endblock %}

core/templates/core/competicion_update_form.html
{% extends "core/base.html" %}

{% block contenido %}
  <div class="container mt-5">
    <form method="post" enctype="multipart/form-data">
      {% csrf_token %}
      <div class="mb-3">
        <label for="{{ form.nombre.id_for_label }}" class="form-label">Nombre de la Competición:</label>
        {{ form.nombre }}
      </div>
      <div class="mb-3">
        <label for="{{ form.lugar.id_for_label }}" class="form-label">Lugar:</label>
        {{ form.lugar }}
      </div>
      <div class="mb-3">
        <label for="{{ form.foto.id_for_label }}" class="form-label">Foto:</label>
        {{ form.foto }}
      </div>
      <div class="mb-3">
        <label for="{{ form.fechaCreacion.id_for_label }}" class="form-label">Fecha de Creación:</label>
        {{ form.fechaCreacion }}
      </div>
      <div class="mb-3">
        <label for="{{ form.fechaModificacion.id_for_label }}" class="form-label">Fecha de Modificación:</label>
        {{ form.fechaModificacion }}
      </div>
      <input type="submit" class="btn btn-primary" value="Crear">
    </form>
  </div>
{% endblock %}

core/templates/core/equipos_confirm_delete.html
{% extends "core/base.html" %}
{% block contenido %}
<div class="container mt-5">
    <div class="row">
        <div class="col-1"></div>
        <div class="col-10 text-center">
            <form method="post">
                {% csrf_token %}
                <p>¿Seguro que quieres borrar el equipo {{equipo}}?</p>
                {{ form }}
                <input type="submit" value="confirmar" class="btn btn-primary">
                <a href="{% url 'listado' %}" class="btn btn-secondary">Cancelar</a>
            </form>
        </div>
    </div>
</div>

{% endblock %}

core/templates/core/equipos_detail.html
{% extends "core/base.html"%}
{% block contenido %}

<div class="card" style="width: 18rem;">
    {% if equipo.foto %}
    <img class="card-img-top" src="{{ equipo.foto.url }}" alt="{{ equipo.nombre }}">
    {% endif %}
    <div class="card-body">
        <ul class="list-group list-group-flush">
            <li class="list-group-item"><b>Nombre: </b>{{jugador.nombre}}</li>
            <li class="list-group-item"><b>Edad: </b>{{jugador.edad}}</li>
            <li class="list-group-item"><b>Equipo: </b>{{jugador.equipo}}</li>
          </ul>
    </div>
  </div>
{% endblock %}

core/templates/core/equipos_list.html
{% extends "core/base.html" %}

{% block contenido %}
  <div class="container">
    <div class="row">
      <div class="col-1"></div>
      <div class="col-10">
        {% for equipo in equipos_list %}
          <div class="card mb-3" style="max-width: 1200px;">
            <div class="row g-0">
              <div class="col-4">
                {% if equipo.foto %}
                  <img src="{{ equipo.foto.url }}" class="img-fluid rounded-start" alt="imagen de {{ equipo.nombre }}">
                {% endif %}
              </div>
              <div class="col-8">
                <div class="card-body">
                  <h5 class="card-title">{{ equipo.nombre }} (Creado por {{ equipo.responsable }})</h5>
                  <p class="card-text">{{ equipo.categoria }}</p>
                  
                  <p class="card-text"><small class="text-muted">Creacion: {{ equipo.fechaCreacion }}</small></p>
                  <p class="card-text"><small class="text-muted">Jugadores:</small></p>
                  {% for jugador in equipo.jugador_set.all %}
                    <p class="card-text"><small class="text-muted">{{ jugador.nombre }}</small></p>
                  {% endfor %}

                  {% if equipo.responsable == request.user %}
                    <p class="card-text">
                      <small class="text-muted">
                        <a href="{% url 'borrar' equipo.id %}">borrar</a>
                      </small>
                    </p>
                    <p class="card-text">
                      <small class="text-muted">
                        <a href="{% url 'modificar' equipo.id %}">modificar</a>
                      </small>
                    </p>
                  {% endif %}
                </div>
              </div>
            </div>
          </div>
        {% endfor %}
      </div>
      <div class="col-1"></div>
    </div>
  </div>
{% endblock %}

core/templates/core/equipos_update_form.html
{% extends "core/base.html" %}

{% block contenido %}
  <div class="container mt-5">
    <form method="post" enctype="multipart/form-data">
      {% csrf_token %}
      <div class="mb-3">
        <label for="{{ form.nombre.id_for_label }}" class="form-label">Nombre del Equipo:</label>
        {{ form.nombre }}
      </div>
      <div class="mb-3">
        <label for="{{ form.categoria.id_for_label }}" class="form-label">Categoría:</label>
        {{ form.categoria }}
      </div>
      <div class="mb-3">
        <label for="{{ form.competicion.id_for_label }}" class="form-label">Competicion:</label>
        {{ form.competicion }}
      </div>
      <div class="mb-3">
        <label for="{{ form.fechaCreacion.id_for_label }}" class="form-label">Fecha de Creación:</label>
        {{ form.fechaCreacion }}
      </div>
      <div class="mb-3">
        <label for="{{ form.foto.id_for_label }}" class="form-label">Foto:</label>
        {{ form.foto }}
      </div>
      <input type="submit" class="btn btn-primary" value="Crear">
    </form>
  </div>
{% endblock %}

core/templates/core/index.html
{% extends "core/base.html" %}
{% block contenido %}
<div class="container mt-3">
    <div class="row">
        <div class="col p-3 bg-secondary text-white text-center">
            <h1>Portada</h1>
        </div>
    </div>
</div>

{% endblock %}

core/templates/core/jugador_confirm_delete.html
{% extends "core/base.html" %}
{% block contenido %}
<div class="container mt-5">
    <div class="row">
        <div class="col-1"></div>
        <div class="col-10 text-center">
            <form method="post">
                {% csrf_token %}
                <p>¿Seguro que quieres borrar el jugador {{jugador}}?</p>
                {{ form }}
                <input type="submit" value="confirmar" class="btn btn-primary">
                <a href="{% url 'listadoJugador' %}" class="btn btn-secondary">Cancelar</a>
            </form>
        </div>
    </div>
</div>

{% endblock %}

core/templates/core/jugador_form.html
{% extends "core/base.html" %}

{% block contenido %}
  <div class="container mt-5">
    <form method="post" enctype="multipart/form-data">
      {% csrf_token %}
      <div class="mb-3">
        <label for="{{ form.nombre.id_for_label }}" class="form-label">Nombre del Jugador:</label>
        {{ form.nombre }}
      </div>
      <div class="mb-3">
        <label for="{{ form.correo.id_for_label }}" class="form-label">Correo Electrónico:</label>
        {{ form.correo }}
      </div>
      <div class="mb-3">
        <label for="{{ form.edad.id_for_label }}" class="form-label">Edad:</label>
        {{ form.edad }}
      </div>
      <div class="mb-3">
        <label for="{{ form.foto.id_for_label }}" class="form-label">Foto:</label>
        {{ form.foto }}
      </div>
      <div class="mb-3">
        <label for="{{ form.equipo.id_for_label }}" class="form-label">Equipo:</label>
        {{ form.equipo }}
      </div>
      <div class="mb-3">
        <label for="{{ form.fechaCreacion.id_for_label }}" class="form-label">Fecha de Creación:</label>
        {{ form.fechaCreacion }}
      </div>
      <div class="mb-3">
        <label for="{{ form.fechaModificacion.id_for_label }}" class="form-label">Fecha de Modificación:</label>
        {{ form.fechaModificacion }}
      </div>
      <input type="submit" class="btn btn-primary" value="Crear">
    </form>
  </div>
{% endblock %}

core/templates/core/jugador_list.html
{% extends "core/base.html" %}

{% block contenido %}
  <div class="container">
    <div class="row">
      <div class="col-1"></div>
      <div class="col-10">
        {% for jugador in jugador_list %}
          <div class="card mb-3" style="max-width: 1200px;">
            <div class="row g-0">
              <div class="col-4">
                {% if jugador.foto %}
                  <img src="{{ jugador.foto.url }}" class="img-fluid rounded-start" alt="imagen de {{ jugador.nombre }}">
                {% endif %}
              </div>
              <div class="col-8">
                <div class="card-body">
                  <a href="{%url 'jugadorDetalle' jugador.id %}"><h5 class="card-title">{{ jugador.nombre }} </h5></a>
                  <p class="card-text">Edad: {{ jugador.edad }}</p>
                  <p class="card-text">Equipo: {{ jugador.equipo }}</p>

                  {% if jugador.responsable == request.user %}
                    <p class="card-text">
                      <small class="text-muted">
                        <a href="{% url 'borrarJugador' jugador.id %}">borrar</a>
                      </small>
                    </p>
                    <p class="card-text">
                      <small class="text-muted">
                        <a href="{% url 'modificarJugador' jugador.id %}">modificar</a>
                      </small>
                    </p>
                  {% endif %}
                </div>
              </div>
            </div>
          </div>
        {% endfor %}
      </div>
      <div class="col-1"></div>
    </div>
  </div>
{% endblock %}

core/templates/core/jugador_update_form.html
{% extends "core/base.html" %}

{% block contenido %}
  <div class="container mt-5">
    <form method="post" enctype="multipart/form-data">
      {% csrf_token %}
      <div class="mb-3">
        <label for="{{ form.nombre.id_for_label }}" class="form-label">Nombre del Jugador:</label>
        {{ form.nombre }}
      </div>
      <div class="mb-3">
        <label for="{{ form.correo.id_for_label }}" class="form-label">Correo Electrónico:</label>
        {{ form.correo }}
      </div>
      <div class="mb-3">
        <label for="{{ form.edad.id_for_label }}" class="form-label">Edad:</label>
        {{ form.edad }}
      </div>
      <div class="mb-3">
        <label for="{{ form.foto.id_for_label }}" class="form-label">Foto:</label>
        {{ form.foto }}
      </div>
      <div class="mb-3">
        <label for="{{ form.equipo.id_for_label }}" class="form-label">Equipo:</label>
        {{ form.equipo }}
      </div>
      <div class="mb-3">
        <label for="{{ form.fechaCreacion.id_for_label }}" class="form-label">Fecha de Creación:</label>
        {{ form.fechaCreacion }}
      </div>
      <div class="mb-3">
        <label for="{{ form.fechaModificacion.id_for_label }}" class="form-label">Fecha de Modificación:</label>
        {{ form.fechaModificacion }}
      </div>
      <input type="submit" class="btn btn-primary" value="Crear">
    </form>
  </div>
{% endblock %}